### ISSUE TITLE
Crash when load model created by GridSearchCV

### ISSUE THREAD

**Issue by TrickyPells** [TrickyPells/cLASpy_T#61]
When loading model created after a GridSearchCV, the cLASpy_GUI crashes

**Comment by TrickyPells** [comment]
Traceback (most recent call last):
  File "cLASpy_GUI.py", line 2007, in get_model
    self.open_model()
  File "cLASpy_GUI.py", line 2044, in open_model
    scaler = model['scaler']
TypeError: 'GridSearchCV' object is not subscriptable

**Comment by TrickyPells** [comment]
Fix with 564e47dd3205083ef1ea339caea656f8914a2a1c
