### ISSUE TITLE
Error for prediction for data with no target field

### ISSUE THREAD

**Issue by TrickyPells** [TrickyPells/cLASpy_T#86]
```Step 2/6: Formatting data as pandas.DataFrame...
Traceback (most recent call last):
    File "C:\Programs\cLASpy_T\cLASpy_T.py", line 593, in <module>
      predict(args)
    File "C:\Programs\cLASpy_T\cLASpy_T.py", line 512, in predict
      step2 = predicter.format_dataset(verbose=True)
    File "C:\Programs\cLASpy_T\cLASpy_Classes.py", line 810, in format_dataset
      self.data, self.target = self.load_data_las()
    File "C:\Programs\cLASpy_T\cLASpy_Classes.py", line 763, in load_data_las
      data.drop(columns=self.target_name, inplace=True)  # Drop target field from data
    File "c:\Users\Admin_Xav\Venvs\claspy_t\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
      return func(*args, **kwargs)
    File "c:\Users\Admin_Xav\Venvs\claspy_t\lib\site-packages\pandas\core\frame.py", line 4957, in drop
      return super().drop(
    File "c:\Users\Admin_Xav\Venvs\claspy_t\lib\site-packages\pandas\core\generic.py", line 4259, in drop
      raise ValueError(
ValueError: Need to specify at least one of 'labels', 'index' or 'columns'
```

**Comment by TrickyPells** [comment]
Fix with Pull Request #89.
