### ISSUE TITLE
Error Loading CSV file

### ISSUE THREAD

**Issue by TrickyPells** [TrickyPells/cLASpy_T#87]
```
Step 1/7: Formatting data as pandas.DataFrame...
Traceback (most recent call last):
  File "cLASpy_T.py", line 591, in <module>
    train(args)
  File "cLASpy_T.py", line 444, in train
    step1 = trainer.format_dataset(verbose=True)
  File "D:\01-SAVED\Code_Source\Repositories\cLASpy_T\cLASpy_Classes.py", line 807, in format_dataset
    self.data, self.target = self.load_data_csv()
  File "D:\01-SAVED\Code_Source\Repositories\cLASpy_T\cLASpy_Classes.py", line 731, in load_data_csv
    target = pd.DataFrame.loc[:, self.target_name]  # use dtype uint8
TypeError: 'property' object is not subscriptable
```

**Comment by TrickyPells** [comment]
Fix with Pull Request #89.
